import PublicPageHero from '@/components/public-page-hero';
import PublicSiteLayout from '@/layouts/public-site-layout';
import { contact } from '@/routes';

const programs = [['Technical training', 'Installation, maintenance, electrical controls, troubleshooting, cold-room installation, commissioning, leak detection, and workplace safety.'], ['Refrigerant management', 'Responsible use through handling training, leak prevention, recovery and recycling, safe decommissioning, and guidance on new technologies.'], ['Energy efficiency', 'Helping professionals and equipment owners reduce consumption through correct sizing, maintenance, insulation, temperature control, and customer education.'], ['Youth & student development', 'Career guidance, mentorship, practical demonstrations, internship referrals, industry visits, competitions, and employment preparation.'], ['Women in HVAC & refrigeration', 'Technical training, mentorship, career guidance, business development, outreach, networking, and leadership opportunities.'], ['Business development', 'Quotation preparation, job costing, customer service, record management, service agreements, quality control, and workplace management.']];

export default function Programs(): React.JSX.Element {
    return <PublicSiteLayout title="Programs & activities"><PublicPageHero eyebrow="Programs & activities" title={<>Work that moves<br />the sector <i className="font-normal">forward.</i></>} copy="The Society organizes programs that improve technical skills, promote safe practices, support environmental responsibility, and connect professionals with industry opportunities." action={{ label: 'Register your interest', route: contact() }} image="https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?auto=format&fit=crop&w=1400&q=85" /><main><section className="px-5 py-24 md:px-10 md:py-32 lg:px-14"><div className="mx-auto max-w-[1328px]"><p className="text-[10px] font-bold tracking-[.18em] text-dark-emerald-700 uppercase">Our program areas</p><div className="mt-8 border-t border-dark-emerald-900/20">{programs.map(([title, copy], index) => <article key={title} className="grid gap-6 border-b border-dark-emerald-900/20 py-8 md:grid-cols-12 md:gap-10"><span className="font-serif text-3xl text-cobalt-blue-700 md:col-span-1">0{index + 1}</span><h2 className="text-2xl font-semibold tracking-[-.04em] md:col-span-4">{title}</h2><p className="max-w-xl text-sm leading-6 text-dark-emerald-700 md:col-span-6 md:col-start-7">{copy}</p></article>)}</div></div></section><section className="bg-cobalt-blue-100 px-5 py-24 md:px-10 md:py-32 lg:px-14"><div className="mx-auto grid max-w-[1328px] gap-12 lg:grid-cols-12"><h2 className="font-serif text-5xl leading-[.9] tracking-[-.05em] lg:col-span-5 md:text-6xl">Programs that meet people where the work happens.</h2><div className="lg:col-span-5 lg:col-start-8"><p className="text-base leading-7 text-dark-emerald-700">Every program is built around practical outcomes. Information on dates, locations, participation requirements, registration, and results will be published for each activity.</p><a href="#program-list" className="mt-8 inline-flex border-b border-dark-emerald-900 pb-2 text-[11px] font-bold tracking-[.14em] uppercase">View current opportunities</a></div></div></section></main></PublicSiteLayout>;
}
